
export const LOGIN = 'LOGIN';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const LOGOUT = 'LOGOUT';
export const USER_PROFILE = 'USER_PROFILE'
export const FILTER_WATCHLIST = 'FILTER_WATCHLIST'
export const ACTIVE_USER = 'ACTIVE_USER';

export const ALL_VENUES = "ALL_VENUES"
export const SEARCH_VENUES = "SEARCH_VENUES"
export const VIEWED_VENUES = "VIEWED_VENUES"
export const VENUE_DETAIL = "VENUE_DETAIL"
export const MOST_POPULAR_VENUES = "MOST_POPULAR_VENUES"
export const RECOMMENDED_VENUES = "RECOMMENDED_VENUES"
export const ADD_RATING = "ADD_RATING"
export const UPDATE_RATING = "UPDATE_RATING"
export const DELETE_RATINGS = "DELETE_RATINGS"
export const VENUE_REVIEW = "VENUE_REVIEW"
